spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenantDB
    username: user
    password: User1234
  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8081